### ISSUE TITLE
[DQR TECH] Fullstack Nodejs/Flutter - PJ/REMOTO

### ISSUE THREAD

**Issue by DaianeMFirmiano** [programadores-br/geral#1524]
Sobre a vaga
Oportunidade para FULLSTACK NODE.JS + FLUTTER

Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

DE ONDE VOCÊ VAI TRABALHAR?
No melhor lugar, onde você se sentir confortável!

O QUE NOS MOVE:
Desafios! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente, uma Fintech com soluções inovadoras para o mercado de Gift Card.

O QUE ESPERAMOS QUE VOCÊ SAIBA:
Microsserviços altamente escaláveis escritos em TypeScript/NodeJS;
Aplicações de Front-end com Flutter;
Utilizando uma arquitetura funcional para Firebase/Google Functions;
Continuous Integration e Deployment (CI/CD) para Google e Firebase;
Estrutura de dados em Firestore.

O QUE SERIA LEGAL SE VOCÊ SOUBESSE:
High throughput APIs para comunicação externa;
Monitoramento e logs via Stack Drive;
Ambiente Analítico separado via orquestração de eventos Segment;
BigData com Google BigQuery;
Trabalhar com sistemas distribuídos de grande escala;
Colaborar com a criação de sistemas funcionais (microfunctions);
Ter conhecimento de metodologias ágeis para o desenvolvimento;

O QUE OFERECEMOS PARA VOCÊ?
Contratação PJ até 15k - atuação 100% remota;
Recesso remunerado;
13º pagamento.

Aguardamos seu contato!

Meu contato direto: (51) 989678273
daiane.firmiano@dqrtech.com.br

Acesse nosso portal de carreiras: https://dqrtech.com.br/oportunidades/

**Comment by gsabreudev** [comment]
#vem ser DQR Tech!!!
