### ISSUE TITLE
[DQR TECH] Fullstack Nodejs/Angular - REMOTO

### ISSUE THREAD

**Issue by DaianeMFirmiano** [programadores-br/geral#1526]
Oportunidade para Fullstack Nodejs/Angular - REMOTO

Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

DE ONDE VOCÊ VAI TRABALHAR?
No formato híbrido ou remoto. Para híbrido, precisará eventualmente ir para ao Cliente no Bairro Itaim Bibi, Faria Lima/SP.

O QUE NOS MOVE:
Desafios! É por isso que estamos em busca de excelentes profissionais para atuar em nossos times, no seguimento bancário.

SEU DESAFIO SERÁ:
Trabalhar com pequenas melhorias; manutenção; sustentação e suporte em sistemas da área financeira/bancária.

O QUE ESPERAMOS QUE VOCÊ SAIBA:
Node
Angular
Git, Gitflow
MongoDB; SQL server;
AWS (SQS;SNS; Cloud Formation);
RabbitMQ ou Kafka;
DevOps (Docker; Rancher)
SOLID.

O QUE SERIA UM DIFERECIAL:
.NET core;
NestJS;
Testes Unitários.

QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Comprometimento;
Perfil descontraído;
Perfil Proativo.

O QUE OFERECEMOS PARA VOCÊ?
Vale Refeição/Alimentação;
Assistência Médica e Odontológica sem coparticipação;
Seguro de Vida;
Acreditamos no desenvolvimento contínuo de nossos colaboradores,
dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
Auxílio-creche;
Aqui a sua indicação vale premiação;
No seu aniversário você recebe mimos;
Horário-flexível (conforme o cliente);
Contrato CLT (40 hrs semanais).

Aguardamos seu contato!

Meu contato direto: (51) 989678273
daiane.firmiano@dqrtech.com.br

Acesse nosso portal de carreiras: https://dqrtech.com.br/oportunidades/

**Comment by gsabreudev** [comment]
#vem ser DQR Tech!!!
