### ISSUE TITLE
Criar labels no repositório

### ISSUE THREAD

**Issue by guibranco** [programadores-br/geral#2218]
@carvalholeo poderia criar as labels no repositório para que elas sejam atribuidas aos issues (se preferir pode me dar acesso de mantenedor e eu crio as labels).

**Comment by guibranco** [comment]
@carvalholeo se preferir pode usar esse snippet de código no Postman para copiar as labels de um outro repositório de vagas para este também...

https://gist.github.com/guibranco/4a10858cf5815209734512b8bdf95996

**Comment by carvalholeo** [comment]
Que engraçado, mesmo com você marcando e esse tivo de notificação ativada, eu não fui avisado sobre...

Vou dar uma olhada aqui e já te retorno!

**Comment by guibranco** [comment]
Sem problemas @carvalholeo, obrigado!

**Comment by guibranco** [comment]
Adicionado!
