### ISSUE TITLE
[Alphaville – Barueri/SP] Pessoa Desenvolvedora Fullstack PHP @ dqr.tech

### ISSUE THREAD

**Issue by AndrewsCunha** [programadores-br/geral#2366]
Sobre a DQR TECH | Qualidade do começo ao fim:
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting. 

DE ONDE VOCÊ VAI TRABALHAR? 
Presencialmente em Alphaville – Barueri/SP.

O QUE NOS MOVE: 
Tecnologia & Pessoas! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente que cuida dos viajantes em qualquer parte do mundo. 

O SEU DESAFIO SERÁ: 
Atuará como Fullstack numa squad ágil com demandas e projetos em sistema legado em ASP Net Clássico, com possibilidade na sua reestruturação para tecnologias mais atuais de mercado.

O QUE ESPERAMOS QUE VOCÊ SAIBA: 
Experiência em construção de projetos de desenvolvimento de software utilizando:

PHP

ASP .Net Clássico e C#/.NET Core

HTML/ CSS/JS

SQL Server

Cloud Azure

Microsserviços

GitHub

O QUE SERIA LEGAL SE VOCÊ SOUBESSE: 
Ter atuado no setor de Seguro Viagem; 

Ter atuado com meios de pagamentos;

Experiência em modelagem de dados em DDD. 

QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER: 
Liderança, habilidades de comunicação, boa didática, iniciativa (buscar soluções).

O QUE OFERECEMOS PARA VOCÊ? 
Contratação PJ com 30 dias de recesso remunerado;

Disponibilização de notebook;

Descontos em instituições de ensino superior e academias;

Bonificação anual.

#### Alocação
- Alocado
- Presencial

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

#### Período
- Full time

#### Remuneração
- R$ 12k - R$ 15k

Link para inscrição: https://www.dqrtech.com.br/vagas/pessoa-desenvolvedora-fullstack-php-pl-sr/

Recrutador Andrews - andrews.cunha@dqrtech.com

**Comment by DaianeMFirmiano** [comment]
Ótima oportunidade!!
