### ISSUE TITLE
[Remoto] Fullstack Node.js Developer Sênior na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [programadores-br/geral#2761]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/fullstack-nodejs-developer-senior-215812480?utm_source=github&utm_medium=programadores-br-geral&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Squadfy está em busca de uma pessoa desenvolvedora full-stack para integrar sua equipe!</p>
<p>Somos uma consultoria de tecnologia focada na transformação digital do mercado e no desenvolvimento de produtos digitais para empresas de grande porte.</p>
<p>Nessa posição, você lidará com a criação de sistemas do 0 em colaboração com outras equipes, operando de forma totalmente remota.</p>
<p>Nosso trabalho é impulsionado pela tecnologia com ênfase na Experiência do Usuário.</p>
<p>Aqui, cada membro da equipe é fundamental para o resultado final. Você terá espaço para contribuir com opiniões, sugestões e decisões, além de participar ativamente na definição e criação de oportunidades no projeto. Você também terá a oportunidade de trabalhar ao lado de profissionais experientes e impulsionar sua carreira.</p>
## Squadfy: 
 <p>A Squadfy é a casa de pessoas brilhantes com conhecimento de mercado e visão disruptiva para acelerar resultados.</p>
<p>Nós transformamos os desafios de negócio de grandes empresas através de uma metodologia pioneira com entregas em 90 dias.&nbsp;</p><a href='https://coodesh.com/companies/squadfy'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Docker 
- Node.js 
- Typescript 
- GIT 
- MySQL 
- MongoDB 
- Tailwind CSS 
- Serverless
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em Node.js, Docker, PostgreSQL, MySQL, MongoDB, React, Tailwind 
- Conhecimento em TypeScript 
- Conhecimento em Testes 
- Conhecimento em controle de versão (Git, GitFlow) 
- Experiência com filas
## Diferenciais: 
 - Conhecimentos em AWS 
- Conhecimentos em Serverless 
- Conhecimentos em sistemas RPA.
## Benefícios: 
 - 13º Salário; 
- 30 dias férias remuneradas; 
- R$ 500,00 de ajuda de custo.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Node.js Developer Sênior na Squadfy](https://coodesh.com/jobs/fullstack-nodejs-developer-senior-215812480?utm_source=github&utm_medium=programadores-br-geral&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by smithereens1998** [comment]
Enviado

Meu Linkedlin: https://www.linkedin.com/in/tiago-vilela-15a548239/
